version: "2.3"

networks:
  web:
    external: true

services:
  covid-nginx:
    container_name: covid-nginx
    image: nginx:alpine
    restart: unless-stopped
    networks:
       - web
    expose:
       - 80
#    ports:
#      - 8000:80
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:covid.view.urbanobservatory.ac.uk"
    logging:
      driver: json-file
      options:
        max-size: '1024k'
        max-file: '10'
    volumes:
      - ./viewer:/usr/share/nginx/html:ro
      - ./output:/usr/src/app:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  covid-notebook:
    container_name: covid-notebook
    image: jupyter/datascience-notebook
    restart: unless-stopped
    environment:
      - JUPYTER_ENABLE_LAB=yes
#      - GRANT_SUDO=yes
    logging:
      driver: json-file
      options:
        max-size: '1024k'
        max-file: '10'
    volumes:
      - ./:/home/jovyan/movement-dashboard:rw
